export const videos = [
  {
    thumbnail: "https://placeholder.com/400",
    title: "Lorem ipsum dolor sit amet.",
    user: "MUSIC SKY",
    avatar: "https://placeholder.com/80",
    views: "20k",
    date: "22hrs ago",
    duration: "5:32:12",
  },
  {
    thumbnail: "https://placeholder.com/400",
    title: "Lorem ipsum dolor sit amet.",
    user: "MUSIC SKY",
    avatar: "https://placeholder.com/80",
    views: "20k",
    date: "22hrs ago",
    duration: "5:32:12",
  },
  {
    thumbnail: "https://placeholder.com/400",
    title: "Lorem ipsum dolor sit amet.",
    user: "MUSIC SKY",
    avatar: "https://placeholder.com/80",
    views: "20k",
    date: "22hrs ago",
    duration: "5:32:12",
  },
  {
    thumbnail: "https://placeholder.com/400",
    title: "Lorem ipsum dolor sit amet.",
    user: "MUSIC SKY",
    avatar: "https://placeholder.com/80",
    views: "20k",
    date: "22hrs ago",
    duration: "5:32:12",
  },
  {
    thumbnail: "https://placeholder.com/400",
    title: "Lorem ipsum dolor sit amet.",
    user: "MUSIC SKY",
    avatar: "https://placeholder.com/80",
    views: "20k",
    date: "22hrs ago",
    duration: "5:32:12",
  },
  {
    thumbnail: "https://placeholder.com/400",
    title: "Lorem ipsum dolor sit amet.",
    user: "MUSIC SKY",
    avatar: "https://placeholder.com/80",
    views: "20k",
    date: "22hrs ago",
    duration: "5:32:12",
  },
  {
    thumbnail: "https://placeholder.com/400",
    title: "Lorem ipsum dolor sit amet.",
    user: "MUSIC SKY",
    avatar: "https://placeholder.com/80",
    views: "20k",
    date: "22hrs ago",
    duration: "5:32:12",
  },
  {
    thumbnail: "https://placeholder.com/400",
    title: "Lorem ipsum dolor sit amet.",
    user: "MUSIC SKY",
    avatar: "https://placeholder.com/80",
    views: "20k",
    date: "22hrs ago",
    duration: "5:32:12",
  },
  {
    thumbnail: "https://placeholder.com/400",
    title: "Lorem ipsum dolor sit amet.",
    user: "MUSIC SKY",
    avatar: "https://placeholder.com/80",
    views: "20k",
    date: "22hrs ago",
    duration: "5:32:12",
  },
];

export const shorts = [
  {
    thumbnail: "https://placeholder.com/220x390",
    title: "When You Find Korean Al Girl...",
    views: "5m",
  },
  {
    thumbnail: "https://placeholder.com/220x390",
    title: "When You Find Korean Al Girl...",
    views: "5m",
  },
  {
    thumbnail: "https://placeholder.com/220x390",
    title: "When You Find Korean Al Girl...",
    views: "5m",
  },
  {
    thumbnail: "https://placeholder.com/220x390",
    title: "When You Find Korean Al Girl...",
    views: "5m",
  },
  {
    thumbnail: "https://placeholder.com/220x390",
    title: "When You Find Korean Al Girl...",
    views: "5m",
  },
  {
    thumbnail: "https://placeholder.com/220x390",
    title: "When You Find Korean Al Girl...",
    views: "5m",
  },
  {
    thumbnail: "https://placeholder.com/220x390",
    title: "When You Find Korean Al Girl...",
    views: "5m",
  },
  {
    thumbnail: "https://placeholder.com/220x390",
    title: "When You Find Korean Al Girl...",
    views: "5m",
  },
  {
    thumbnail: "https://placeholder.com/220x390",
    title: "When You Find Korean Al Girl...",
    views: "5m",
  },
  {
    thumbnail: "https://placeholder.com/220x390",
    title: "When You Find Korean Al Girl...",
    views: "5m",
  },
  {
    thumbnail: "https://placeholder.com/220x390",
    title: "When You Find Korean Al Girl...",
    views: "5m",
  },
];
