export const movies = [
  {
    title: "Inception",
    image: "banner1.jpg",
    year: "2010",
    cast: "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
    genre: "Sci-Fi",
    duration: "2hr 28min",
    rating: 8.8,
    match: "87%",
    description:
      "A thief who enters the dreams of others to steal secrets from their subconscious gets one last job where he must implant an idea into a CEO's mind.",
    type: "suspense",
    grouping: "Trending",
  },
  {
    title: "Parasite",
    image: "banner2.jpg",
    year: "2019",
    cast: "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong",
    genre: "Drama",
    duration: "2hr 12min",
    rating: 8.6,
    match: "91%",
    description:
      "A poor family cunningly infiltrates a wealthy household, but their easy life takes a dark turn when their deception is threatened with exposure.",
    type: "suspense",
    grouping: "Trending",
  },
  {
    title: "The Shawshank Redemption",
    image: "banner3.jpg",
    year: "1994",
    cast: "Tim Robbins, Morgan Freeman, Bob Gunton",
    genre: "Drama",
    duration: "2hr 22min",
    rating: 9.3,
    match: "94%",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    type: "drama",
    grouping: "Trending",
  },
  {
    title: "Spirited Away",
    image: "banner4.jpg",
    year: "2001",
    cast: "Rumi Hiiragi, Miyu Irino, Mari Natsuki",
    genre: "Adventure",
    duration: "2hr 5min",
    rating: 8.6,
    match: "88%",
    description:
      "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
    type: "fantasy",
    grouping: "Trending",
  },
  {
    title: "Your Name",
    image: "banner5.jpg",
    year: "2016",
    cast: "Ryunosuke Kamiki, Mone Kamishiraishi, Masami Nagasawa",
    genre: "Drama",
    duration: "1hr 46min",
    rating: 8.4,
    match: "90%",
    description:
      "Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?",
    type: "romance",
    grouping: "Trending",
  },
  {
    title: "The Godfather",
    image: "banner6.jpg",
    year: "1972",
    cast: "Marlon Brando, Al Pacino, James Caan",
    genre: "Drama",
    duration: "2hr 55min",
    rating: 9.2,
    match: "93%",
    description:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    type: "crime",
    grouping: "Trending",
  },
  {
    title: "The Dark Knight",
    image: "banner7.jpg",
    year: "2008",
    cast: "Christian Bale, Heath Ledger, Aaron Eckhart",
    genre: "Drama",
    duration: "2hr 32min",
    rating: 9.0,
    match: "92%",
    description:
      "When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.",
    type: "action",
    grouping: "Trending",
  },
  {
    title: "Crouching Tiger, Hidden Dragon",
    image: "banner8.jpg",
    year: "2000",
    cast: "Yun-Fat Chow, Michelle Yeoh, Ziyi Zhang",
    genre: "Adventure",
    duration: "2hr",
    rating: 7.8,
    match: "85%",
    description:
      "Two warriors in pursuit of a stolen sword and a notorious fugitive are led to an impetuous, physically skilled, adolescent nobleman's daughter, who is at a crossroads in her life.",
    type: "action",
    grouping: "Asian",
  },
  {
    title: "Rashomon",
    image: "banner9.jpg",
    year: "1950",
    cast: "Toshiro Mifune, Machiko Kyô, Masayuki Mori",
    genre: "Drama",
    duration: "1hr 28min",
    rating: 8.2,
    match: "87%",
    description:
      "The rape of a bride and the murder of her samurai husband are recalled from the perspectives of a bandit, the bride, the samurai's ghost, and a woodcutter.",
    type: "mystery",
    grouping: "Asian",
  },
  {
    title: "Oldboy",
    image: "banner10.jpg",
    year: "2003",
    cast: "Choi Min-sik, Yoo Ji-Tae, Kang Hye-jeong",
    genre: "Drama",
    duration: "2hr",
    rating: 8.4,
    match: "89%",
    description:
      "After being kidnapped and imprisoned for 15 years, Oh Dae-Su is released, only to find that he must find his captor in 5 days.",
    type: "thriller",
    grouping: "Asian",
  },
  {
    title: "Seven Samurai",
    image: "banner11.jpg",
    year: "1954",
    cast: "Toshirô Mifune, Takashi Shimura, Keiko Tsushima",
    genre: "Drama",
    duration: "3hr 27min",
    rating: 8.6,
    match: "90%",
    description:
      "A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.",
    type: "action",
    grouping: "Asian",
  },
  {
    title: "Memories of Murder",
    image: "banner12.jpg",
    year: "2003",
    cast: "Kang-ho Song, Sang-kyung Kim, Roe-ha Kim",
    genre: "Drama",
    duration: "2hr 11min",
    rating: 8.1,
    match: "86%",
    description:
      "In a small Korean province in 1986, three detectives struggle with the case of multiple young women being found raped and murdered by an unknown culprit.",
    type: "thriller",
    grouping: "Asian",
  },
  {
    title: "A Moment to Remember",
    image: "banner13.jpg",
    year: "2004",
    cast: "Woo-sung Jung, Ye-jin Son, Jong-hak Baek",
    genre: "Drama",
    duration: "2hr 24min",
    rating: 8.2,
    match: "88%",
    description:
      "A young couple's enduring love is tested when one of them is diagnosed with Alzheimer's disease.",
    type: "romance",
    grouping: "Asian",
  },
  {
    title: "Life of Pi",
    image: "banner14.jpg",
    year: "2012",
    cast: "Suraj Sharma, Irrfan Khan, Adil Hussain",
    genre: "Adventure",
    duration: "2hr 7min",
    rating: 7.9,
    match: "86%",
    description:
      "A young man who survives a disaster at sea is hurtled into an epic journey of adventure and discovery. While cast away, he forms an unexpected connection with another survivor: a fearsome Bengal tiger.",
    type: "adventure",
    grouping: "Trending",
  },
  {
    title: "Inception",
    top: "1.png",
    image: "banner1.jpg",
    year: "2010",
    cast: "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
    genre: "Sci-Fi",
    duration: "2hr 28min",
    rating: 8.8,
    match: "87%",
    description:
      "A thief who enters the dreams of others to steal secrets from their subconscious gets one last job where he must implant an idea into a CEO's mind.",
    type: "suspense",
    grouping: "Top",
  },
  {
    title: "Parasite",
    top: "2.png",
    image: "banner2.jpg",
    year: "2019",
    cast: "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong",
    genre: "Drama",
    duration: "2hr 12min",
    rating: 8.6,
    match: "91%",
    description:
      "A poor family cunningly infiltrates a wealthy household, but their easy life takes a dark turn when their deception is threatened with exposure.",
    type: "suspense",
    grouping: "Top",
  },
  {
    title: "The Shawshank Redemption",
    image: "banner3.jpg",
    top: "3.png",
    year: "1994",
    cast: "Tim Robbins, Morgan Freeman, Bob Gunton",
    genre: "Drama",
    duration: "2hr 22min",
    rating: 9.3,
    match: "94%",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    type: "drama",
    grouping: "Top",
  },
  {
    title: "Spirited Away",
    image: "banner4.jpg",
    top: "4.png",
    year: "2001",
    cast: "Rumi Hiiragi, Miyu Irino, Mari Natsuki",
    genre: "Adventure",
    duration: "2hr 5min",
    rating: 8.6,
    match: "88%",
    description:
      "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
    type: "fantasy",
    grouping: "Top",
  },
  {
    title: "Your Name",
    image: "banner5.jpg",
    year: "2016",
    top: "5.png",
    cast: "Ryunosuke Kamiki, Mone Kamishiraishi, Masami Nagasawa",
    genre: "Drama",
    duration: "1hr 46min",
    rating: 8.4,
    match: "90%",
    description:
      "Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?",
    type: "romance",
    grouping: "Top",
  },
  {
    title: "The Godfather",
    top: "6.png",
    image: "banner6.jpg",
    year: "1972",
    cast: "Marlon Brando, Al Pacino, James Caan",
    genre: "Drama",
    duration: "2hr 55min",
    rating: 9.2,
    match: "93%",
    description:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    type: "crime",
    grouping: "Top",
  },
  {
    title: "The Dark Knight",
    top: "7.png",
    image: "banner7.jpg",
    year: "2008",
    cast: "Christian Bale, Heath Ledger, Aaron Eckhart",
    genre: "Drama",
    duration: "2hr 32min",
    rating: 9.0,
    match: "92%",
    description:
      "When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.",
    type: "action",
    grouping: "Top",
  },
  {
    title: "Crouching Tiger, Hidden Dragon",
    image: "banner8.jpg",
    top: "8.png",
    year: "2000",
    cast: "Yun-Fat Chow, Michelle Yeoh, Ziyi Zhang",
    genre: "Adventure",
    duration: "2hr",
    rating: 7.8,
    match: "85%",
    description:
      "Two warriors in pursuit of a stolen sword and a notorious fugitive are led to an impetuous, physically skilled, adolescent nobleman's daughter, who is at a crossroads in her life.",
    type: "action",
    grouping: "Top",
  },
  {
    title: "Rashomon",
    image: "banner9.jpg",
    year: "1950",
    top: "9.png",
    cast: "Toshiro Mifune, Machiko Kyô, Masayuki Mori",
    genre: "Drama",
    duration: "1hr 28min",
    rating: 8.2,
    match: "87%",
    description:
      "The rape of a bride and the murder of her samurai husband are recalled from the perspectives of a bandit, the bride, the samurai's ghost, and a woodcutter.",
    type: "mystery",
    grouping: "Top",
  },
  {
    title: "Oldboy",
    image: "banner10.jpg",
    year: "2003",
    top: "10.png",
    cast: "Choi Min-sik, Yoo Ji-Tae, Kang Hye-jeong",
    genre: "Drama",
    duration: "2hr",
    rating: 8.4,
    match: "89%",
    description:
      "After being kidnapped and imprisoned for 15 years, Oh Dae-Su is released, only to find that he must find his captor in 5 days.",
    type: "thriller",
    grouping: "Top",
  },
];
